Учебный проект: консольные забавы
htmlacademy-nodejs/311131-buy-and-sell-3 pull request #2
Opened 2020-02-21 15:18 UTC by lissergey

2020-02-23 19:37 UTC, dean992008 requested changes

2020-02-23 19:37 UTC, dean992008 commented on src/constants.js
> +  module.exports.DEFAULT_COMMAND = `--help`;
Я бы предложил объявлять все переменые как клоакальные после чего экспортировать их как объект. 
Например: 
```
module.exports = {
  DEFAULT_COMMAND,
  USER_ARGV_INDEX,
  ExitCode
}
```

2020-02-23 19:37 UTC, dean992008 commented on src/service/cli/generate.js
> +  const fs = require(`fs`);
В редакторе нужно настроить `editorconfig` и `eslint`(если уже не установлены) и выполнить автоформатирование JS файлов.

2020-02-23 19:37 UTC, dean992008 commented on src/service/cli/generate.js
> +   offer: `offer`,
Ключи в перечислении должны быть UPPERCASE
https://up.htmlacademy.ru/nodejs/3/criteries#b7

2020-02-23 19:37 UTC, dean992008 commented on src/utils.js
> +module.exports.getRandomInt = (min, max) => {
Тоже методы нужно объявить как локальные после чего в конце модуля экспортировать.

2020-02-25 11:28 UTC, dean992008 commented on src/service/cli/generate.js
> +   offer: `offer`,
Здесь не совсем верно, большыми буквами должны быть ключи:
```
const OFFER_TYPE = {
    OFFER: `offer`,
    SALE: `sale`,
};
```

2020-02-25 11:30 UTC, dean992008 commented on src/service/cli/generate.js
> +   offer: `offer`,
Впринципе это не критично я прийму, а ты это поправишь вместе со следующий PR.

2020-02-25 11:30 UTC, merged

2020-02-25 13:30 UTC, lissergey commented on src/service/cli/generate.js
> +   offer: `offer`,
Аналогично должно быть и в
```
 const SumRestrict = {
  MIN: 1000,
  MAX: 100000,
};
```
?